# Generated by Django 5.2.6 on 2025-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('completed_orders', models.PositiveIntegerField()),
                ('avg_rating', models.FloatField()),
                ('score', models.FloatField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_orders', models.FloatField(default=0.7, help_text='وزن تعداد سفارش\u200cها (بین 0 و 1)')),
                ('weight_ratings', models.FloatField(default=0.3, help_text='وزن امتیاز (بین 0 و 1)')),
            ],
            options={
                'verbose_name': 'تنظیمات لیدربورد',
                'verbose_name_plural': 'تنظیمات لیدربورد',
            },
        ),
    ]
